feat: basic quizs front
noted-eip/web pull request #115
Opened 2024-01-06 15:17 UTC by kfleury

#### Description

Fixes #<issue number>

#### Changelog

- [BUGFIX]
- [ENHANCEMENT]
- [DOCS]
- ...

2024-01-07 12:57 UTC, kfleury commented on src/panels/QuizsPanels.tsx
> +        <p>{'No quiz found'}</p>
Trad

2024-01-07 12:57 UTC, kfleury commented on src/panels/QuizsPanels.tsx
> +        <p>{'Your current note haven\'t been found'}</p>
Trad

2024-01-07 12:59 UTC, kfleury commented
Tell me when you put the button

2024-01-12 20:18 UTC, gabriel654165 requested changes

2024-01-12 20:18 UTC, gabriel654165 commented on src/components/view/PanelHeader.tsx
> +        // console.log(panelKey)
remove commentary please

2024-01-12 20:18 UTC, gabriel654165 commented on src/hooks/api/recommendations.ts
> +  // const queryKey = newQuizsCacheKey(currentGroupId, req.noteId)
Remove commentary please if you don't want to implem the cache

2024-01-15 19:37 UTC, gabriel654165 approved these changes

2024-01-16 18:23 UTC, merged